### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vIremAydin**

### CODE REVIEW

**Comment by AlperMumcular** [comment]
a

**Comment by vIremAydin** [comment]
> a
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2071964521 

a reply

**Comment by vIremAydin** [comment]
> a
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2071964521 

2 repylu

**Comment by vIremAydin** [comment]
> 
> a
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2071964521 

a reply
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072121928 

ee

**Comment by vIremAydin** [comment]
> 
> a
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2071964521 

2 repylu
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072122508 

3e3e3e3

**Comment by vIremAydin** [comment]
> 
> 
> a
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2071964521 

a reply
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072121928 

ee
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072122765 

32ee23e

**Comment by vIremAydin** [comment]
**Active**: <p>b bg bg bbb</p>

**Comment by vIremAydin** [comment]
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

vnvnvb

**Comment by Ece-Kahraman** [comment]
> 
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

vnvnvb
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072126465 

a reply

**Comment by vIremAydin** [comment]
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

br reply

**Comment by vIremAydin** [comment]
> 
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

br reply
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072134326 

2.rply

**Comment by vIremAydin** [comment]
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

3.repkyt

**Comment by vIremAydin** [comment]
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

bbnbb

**Comment by vIremAydin** [comment]
> 
> **Active**: <p>b bg bg bbb</p>
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072125400 

3.repkyt
> https://github.com/Ece-Kahraman/Eventium/pull/8#issuecomment-2072138211 

4. reply

**Comment by AlperMumcular** [comment]
**ACTIVE**: <p>test</p>

**Pull request closed without merging**
